version: "3"
services:
    mssql:
        build: ./docker/SQLServer
        environment:
            SA_PASSWORD: "MssqlPass123"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            TZ: Asia/Tokyo 
        ports:
            - "1433:1433"
        container_name: mssql
        hostname: mssql
        volumes:
            - ms-sqlserver-linux-sample-data:/var/opt/mssql
            - ./.dockerVolume/mssql_backup:/backup
volumes:
    ms-sqlserver-linux-sample-data:
        driver: local