version: "3"
services:
  web:
    build:
      context: ./docker/Nginx
    environment:
      BACKEND_HOST: "app:5000"  
    ports: 
      - 80:80
  app:
    build:
      context: .
      dockerfile: ./iidx-dbir-dotnet-blazor/Server/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=mssql;Initial Catalog=dbir_db;User ID=sa;Password=MssqlPass123;Trusted_Connection = true;Integrated Security = false;"
    expose:
      - 5000
    depends_on:
      - mssql
  mssql:
    build: ./docker/SQLServer
    environment:
      SA_PASSWORD: "MssqlPass123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      TZ: Asia/Tokyo 
    ports:
      - "1433:1433"
    container_name: mssql
    hostname: mssql
    volumes:
      - ms-sqlserver-linux-sample-data:/var/opt/mssql
      - ./.dockerVolume/mssql_backup:/backup
volumes:
  ms-sqlserver-linux-sample-data:
    driver: local