apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out dbirchart
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --out dbirchart
        kompose.image-pull-policy: IfNotPresent
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: ConnectionStrings__DefaultConnection
          value: "Data Source=db;Initial Catalog=dbir_db;User ID=sa;Password=MssqlPass123;Trusted_Connection = true;Integrated Security = false;"
        image: iidx-dbir-dotnet_app
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
