apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out dbirchart
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --out dbirchart
        kompose.image-pull-policy: IfNotPresent
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: MSSQL_AGENT_ENABLED
          value: "true"
        - name: SA_PASSWORD
          value: MssqlPass123
        - name: TZ
          value: Asia/Tokyo
        image: iidx-dbir-dotnet_db
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 1433
        resources: {}
      hostname: db
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
